" Managed by Ansible

set nocompatible
colorscheme Tomorrow-Night-Mod
syntax on
set ruler
set linebreak
set tabstop=4
set shiftwidth=4
set nobackup
set nowritebackup
set autoindent
set pastetoggle=<F2>
set mouse=
set hlsearch
set backspace=indent,eol,start
imap <F3> <C-R>=strftime("%Y/%m/%d")<CR>
inoremap <S-Tab> <C-V><Tab>
set spelllang=en_au
filetype plugin indent on
